title: "The Farmoxel Project"
repository: "FaR-Team/devlog"
author: "FaR Team"
description: "This is a devlog for our on-development game."

sass:
  style: compressed

##########################################################################################
######### NO MODIFICAR #########
##########################################################################################
theme: "minima"

rss: rss

encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-loading-lazy

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: 
        - Other
        - Devlog
        - Characters
        - Art
        - Event

comments:
  provider: "utterances"
  utterances:
    repo: "FaR-Team/devlog"
    issue_term: "pathname"
    theme_light: "github-light"
    theme_dark: "github-dark"
